# This is a basic workflow that is manually triggered

name: Manual4 workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        description: 'Branch to deploy'
        default: 'standalone'
        required: true
        type: choice
        options:
        - standalone
        - dev
        - master
      host:
        description: 'Host to deploy'
        default: 'nextjs03'
        required: true
        type: choice
        options:
        - nextjs01
        - nextjs02
        - nextjs03
      environment:
        description: 'REST-API backend'
        default: 'rest'
        required: true
        type: choice
        options:
        - rest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello"
