# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        description: 'Branch to deploy'
        default: 'standalone'
        required: true
        type: choice
        options:
        - standalone
        - dev
        - master
      environment:
        description: 'REST-API backend'
        default: 'rest'
        required: true
        type: choice
        options:
        - rest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a two jobs called "greet" and "greet2"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: '${{ inputs.branch }}'
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          .next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    - name: Install dependencies
      run: |
        set -x
        npm ci
    - name: setup REST-API
      run: |
        ls -la
        cp environments/${{ inputs.environment }} .env.local
        ls -la
    - name: Build with Next.js
      run: |
        pwd
        npm run build
    - name: Setup ssh
      run: |
        pwd
        cd
        pwd
        mkdir ~/.ssh
        cp .github/workflows/id_rsa ~/.ssh/id_rsa
        cp .github/workflows/known_hosts ~/.ssh/known_hosts
        ls -la
    - name: Send greeting
      run: |
        set -x
        echo "Hello ${{ inputs.branch }}"
        #echo $SHELL
        #id
        #pwd
        #uname -a
        #ls -la
        #node -v
        #npm -v
        #npm install
        #ls -la
        #du --one-file-system --max-depth=1 | sort -n
        #cat next.config.js
