# This is a basic workflow that is manually triggered

name: Manual4 workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      branch:
        description: 'Branch to deploy'
        default: 'standalone'
        required: true
        type: choice
        options:
        - standalone
        - dev
        - master
      host:
        description: 'Host to deploy'
        default: 'nextjs03'
        required: true
        type: choice
        options:
        - nextjs01
        - nextjs02
        - nextjs03
      environment:
        description: 'REST-API backend'
        default: 'rest'
        required: true
        type: choice
        options:
        - rest

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs
  VC-Buildy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout selected branch
      uses: actions/checkout@v4
      with:
        ref: '${{ inputs.branch }}'
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Restore cache
      uses: actions/cache@v4
      with:
        path: |
          .next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
    - name: Install dependencies
      run: |
        set -x
        npm ci
